// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: chess.proto

package chesspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChessService_StartGame_FullMethodName = "/chess.ChessService/StartGame"
	ChessService_PlayMove_FullMethodName  = "/chess.ChessService/PlayMove"
)

// ChessServiceClient is the client API for ChessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChessServiceClient interface {
	// search for game
	StartGame(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StartGameRequest, StartGameResponse], error)
	// play move in game
	PlayMove(ctx context.Context, in *PlayMoveRequest, opts ...grpc.CallOption) (*PlayMoveResponse, error)
}

type chessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChessServiceClient(cc grpc.ClientConnInterface) ChessServiceClient {
	return &chessServiceClient{cc}
}

func (c *chessServiceClient) StartGame(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StartGameRequest, StartGameResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChessService_ServiceDesc.Streams[0], ChessService_StartGame_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartGameRequest, StartGameResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChessService_StartGameClient = grpc.BidiStreamingClient[StartGameRequest, StartGameResponse]

func (c *chessServiceClient) PlayMove(ctx context.Context, in *PlayMoveRequest, opts ...grpc.CallOption) (*PlayMoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayMoveResponse)
	err := c.cc.Invoke(ctx, ChessService_PlayMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChessServiceServer is the server API for ChessService service.
// All implementations must embed UnimplementedChessServiceServer
// for forward compatibility.
type ChessServiceServer interface {
	// search for game
	StartGame(grpc.BidiStreamingServer[StartGameRequest, StartGameResponse]) error
	// play move in game
	PlayMove(context.Context, *PlayMoveRequest) (*PlayMoveResponse, error)
	mustEmbedUnimplementedChessServiceServer()
}

// UnimplementedChessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChessServiceServer struct{}

func (UnimplementedChessServiceServer) StartGame(grpc.BidiStreamingServer[StartGameRequest, StartGameResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedChessServiceServer) PlayMove(context.Context, *PlayMoveRequest) (*PlayMoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayMove not implemented")
}
func (UnimplementedChessServiceServer) mustEmbedUnimplementedChessServiceServer() {}
func (UnimplementedChessServiceServer) testEmbeddedByValue()                      {}

// UnsafeChessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChessServiceServer will
// result in compilation errors.
type UnsafeChessServiceServer interface {
	mustEmbedUnimplementedChessServiceServer()
}

func RegisterChessServiceServer(s grpc.ServiceRegistrar, srv ChessServiceServer) {
	// If the following call pancis, it indicates UnimplementedChessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChessService_ServiceDesc, srv)
}

func _ChessService_StartGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChessServiceServer).StartGame(&grpc.GenericServerStream[StartGameRequest, StartGameResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChessService_StartGameServer = grpc.BidiStreamingServer[StartGameRequest, StartGameResponse]

func _ChessService_PlayMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChessServiceServer).PlayMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChessService_PlayMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChessServiceServer).PlayMove(ctx, req.(*PlayMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChessService_ServiceDesc is the grpc.ServiceDesc for ChessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chess.ChessService",
	HandlerType: (*ChessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlayMove",
			Handler:    _ChessService_PlayMove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartGame",
			Handler:       _ChessService_StartGame_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chess.proto",
}
