// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: chess.proto

package chesspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Timeformat    string                 `protobuf:"bytes,3,opt,name=timeformat,proto3" json:"timeformat,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	PreferedColor string                 `protobuf:"bytes,5,opt,name=prefered_color,json=preferedColor,proto3" json:"prefered_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_chess_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chess_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_chess_proto_rawDescGZIP(), []int{0}
}

func (x *StartGameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartGameRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *StartGameRequest) GetTimeformat() string {
	if x != nil {
		return x.Timeformat
	}
	return ""
}

func (x *StartGameRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *StartGameRequest) GetPreferedColor() string {
	if x != nil {
		return x.PreferedColor
	}
	return ""
}

type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	PlayersId     string                 `protobuf:"bytes,3,opt,name=playersId,proto3" json:"playersId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_chess_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chess_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_chess_proto_rawDescGZIP(), []int{1}
}

func (x *StartGameResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *StartGameResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *StartGameResponse) GetPlayersId() string {
	if x != nil {
		return x.PlayersId
	}
	return ""
}

type PlayMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerColor   string                 `protobuf:"bytes,3,opt,name=playerColor,proto3" json:"playerColor,omitempty"`
	Fen           string                 `protobuf:"bytes,4,opt,name=fen,proto3" json:"fen,omitempty"`
	Move          string                 `protobuf:"bytes,5,opt,name=move,proto3" json:"move,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayMoveRequest) Reset() {
	*x = PlayMoveRequest{}
	mi := &file_chess_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMoveRequest) ProtoMessage() {}

func (x *PlayMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chess_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMoveRequest.ProtoReflect.Descriptor instead.
func (*PlayMoveRequest) Descriptor() ([]byte, []int) {
	return file_chess_proto_rawDescGZIP(), []int{2}
}

func (x *PlayMoveRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayMoveRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayMoveRequest) GetPlayerColor() string {
	if x != nil {
		return x.PlayerColor
	}
	return ""
}

func (x *PlayMoveRequest) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *PlayMoveRequest) GetMove() string {
	if x != nil {
		return x.Move
	}
	return ""
}

type PlayMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	NewFen        string                 `protobuf:"bytes,2,opt,name=newFen,proto3" json:"newFen,omitempty"`
	IsLegal       bool                   `protobuf:"varint,3,opt,name=isLegal,proto3" json:"isLegal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayMoveResponse) Reset() {
	*x = PlayMoveResponse{}
	mi := &file_chess_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMoveResponse) ProtoMessage() {}

func (x *PlayMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chess_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMoveResponse.ProtoReflect.Descriptor instead.
func (*PlayMoveResponse) Descriptor() ([]byte, []int) {
	return file_chess_proto_rawDescGZIP(), []int{3}
}

func (x *PlayMoveResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayMoveResponse) GetNewFen() string {
	if x != nil {
		return x.NewFen
	}
	return ""
}

func (x *PlayMoveResponse) GetIsLegal() bool {
	if x != nil {
		return x.IsLegal
	}
	return false
}

var File_chess_proto protoreflect.FileDescriptor

const file_chess_proto_rawDesc = "" +
	"\n" +
	"\vchess.proto\x12\x05chess\"\xa1\x01\n" +
	"\x10StartGameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\x12\x1e\n" +
	"\n" +
	"timeformat\x18\x03 \x01(\tR\n" +
	"timeformat\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12%\n" +
	"\x0eprefered_color\x18\x05 \x01(\tR\rpreferedColor\"g\n" +
	"\x11StartGameResponse\x12\x1c\n" +
	"\tisSuccess\x18\x01 \x01(\bR\tisSuccess\x12\x16\n" +
	"\x06gameId\x18\x02 \x01(\tR\x06gameId\x12\x1c\n" +
	"\tplayersId\x18\x03 \x01(\tR\tplayersId\"\x8d\x01\n" +
	"\x0fPlayMoveRequest\x12\x16\n" +
	"\x06gameId\x18\x01 \x01(\tR\x06gameId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\x12 \n" +
	"\vplayerColor\x18\x03 \x01(\tR\vplayerColor\x12\x10\n" +
	"\x03fen\x18\x04 \x01(\tR\x03fen\x12\x12\n" +
	"\x04move\x18\x05 \x01(\tR\x04move\"\\\n" +
	"\x10PlayMoveResponse\x12\x16\n" +
	"\x06gameId\x18\x01 \x01(\tR\x06gameId\x12\x16\n" +
	"\x06newFen\x18\x02 \x01(\tR\x06newFen\x12\x18\n" +
	"\aisLegal\x18\x03 \x01(\bR\aisLegal2\x8f\x01\n" +
	"\fChessService\x12B\n" +
	"\tStartGame\x12\x17.chess.StartGameRequest\x1a\x18.chess.StartGameResponse(\x010\x01\x12;\n" +
	"\bPlayMove\x12\x16.chess.PlayMoveRequest\x1a\x17.chess.PlayMoveResponseB\x11Z\x0f./chess;chesspbb\x06proto3"

var (
	file_chess_proto_rawDescOnce sync.Once
	file_chess_proto_rawDescData []byte
)

func file_chess_proto_rawDescGZIP() []byte {
	file_chess_proto_rawDescOnce.Do(func() {
		file_chess_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chess_proto_rawDesc), len(file_chess_proto_rawDesc)))
	})
	return file_chess_proto_rawDescData
}

var file_chess_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chess_proto_goTypes = []any{
	(*StartGameRequest)(nil),  // 0: chess.StartGameRequest
	(*StartGameResponse)(nil), // 1: chess.StartGameResponse
	(*PlayMoveRequest)(nil),   // 2: chess.PlayMoveRequest
	(*PlayMoveResponse)(nil),  // 3: chess.PlayMoveResponse
}
var file_chess_proto_depIdxs = []int32{
	0, // 0: chess.ChessService.StartGame:input_type -> chess.StartGameRequest
	2, // 1: chess.ChessService.PlayMove:input_type -> chess.PlayMoveRequest
	1, // 2: chess.ChessService.StartGame:output_type -> chess.StartGameResponse
	3, // 3: chess.ChessService.PlayMove:output_type -> chess.PlayMoveResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chess_proto_init() }
func file_chess_proto_init() {
	if File_chess_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chess_proto_rawDesc), len(file_chess_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chess_proto_goTypes,
		DependencyIndexes: file_chess_proto_depIdxs,
		MessageInfos:      file_chess_proto_msgTypes,
	}.Build()
	File_chess_proto = out.File
	file_chess_proto_goTypes = nil
	file_chess_proto_depIdxs = nil
}
