// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PlanType string

const (
	PlanTypeFreemium PlanType = "freemium"
	PlanTypePremium  PlanType = "premium"
)

func (e *PlanType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanType(s)
	case string:
		*e = PlanType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanType: %T", src)
	}
	return nil
}

type NullPlanType struct {
	PlanType PlanType `json:"plan_type"`
	Valid    bool     `json:"valid"` // Valid is true if PlanType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanType) Scan(value interface{}) error {
	if value == nil {
		ns.PlanType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanType), nil
}

type User struct {
	ID           int32       `json:"_id"`
	Fullname     string      `json:"fullname"`
	Email        string      `json:"email"`
	Password     string      `json:"password"`
	Chesscomname pgtype.Text `json:"chesscomname"`
	Plan         PlanType    `json:"plan"`
	Reviewcount  pgtype.Int4 `json:"reviewcount"`
	Lastreviwed  pgtype.Date `json:"lastreviwed"`
}
