// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PlanType string

const (
	PlanTypeFreemium PlanType = "freemium"
	PlanTypePremium  PlanType = "premium"
)

func (e *PlanType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanType(s)
	case string:
		*e = PlanType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanType: %T", src)
	}
	return nil
}

type NullPlanType struct {
	PlanType PlanType `json:"plan_type"`
	Valid    bool     `json:"valid"` // Valid is true if PlanType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanType) Scan(value interface{}) error {
	if value == nil {
		ns.PlanType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanType), nil
}

type Game struct {
	ID            pgtype.UUID `json:"_id"`
	Gameurl       string      `json:"gameurl"`
	Whiteusername string      `json:"whiteusername"`
	Blackusername string      `json:"blackusername"`
	Whiterating   int32       `json:"whiterating"`
	Blackrating   int32       `json:"blackrating"`
	Playercolor   string      `json:"playercolor"`
	Timeclass     string      `json:"timeclass"`
	Result        string      `json:"result"`
	Issuecount    int32       `json:"issuecount"`
	UserID        int32       `json:"user_id"`
	Createdate    pgtype.Date `json:"createdate"`
}

type Issue struct {
	ID             pgtype.UUID `json:"_id"`
	GameID         pgtype.UUID `json:"game_id"`
	Moveindex      int32       `json:"moveindex"`
	Movesan        string      `json:"movesan"`
	Moveuci        string      `json:"moveuci"`
	Fen            string      `json:"fen"`
	Sidetomove     string      `json:"sidetomove"`
	Playercolor    string      `json:"playercolor"`
	Usercolor      string      `json:"usercolor"`
	Issuetype      string      `json:"issuetype"`
	Playedbestmove bool        `json:"playedbestmove"`
	Bestmove       string      `json:"bestmove"`
	Ponder         string      `json:"ponder"`
	Pv             []string    `json:"pv"`
	Depth          int32       `json:"depth"`
	Scorecp        int32       `json:"scorecp"`
	Mate           int32       `json:"mate"`
	Afterscorecp   int32       `json:"afterscorecp"`
	Aftermate      int32       `json:"aftermate"`
	Winprobbefore  float64     `json:"winprobbefore"`
	Winprobafter   float64     `json:"winprobafter"`
	Playedmoveuci  string      `json:"playedmoveuci"`
	Playedmovesan  string      `json:"playedmovesan"`
	Cpdelta        int32       `json:"cpdelta"`
	Winprobdelta   float64     `json:"winprobdelta"`
	Solution       []string    `json:"solution"`
}

type Puzzle struct {
	ID          string      `json:"_id"`
	Fen         string      `json:"fen"`
	Moves       string      `json:"moves"`
	Rating      int32       `json:"rating"`
	Themes      []string    `json:"themes"`
	Openingtags pgtype.Text `json:"openingtags"`
	Source      pgtype.Text `json:"source"`
	Createdat   pgtype.Date `json:"createdat"`
}

type User struct {
	ID           int32       `json:"_id"`
	Fullname     string      `json:"fullname"`
	Email        string      `json:"email"`
	Password     string      `json:"password"`
	Chesscomname pgtype.Text `json:"chesscomname"`
	Plan         PlanType    `json:"plan"`
	Reviewcount  pgtype.Int4 `json:"reviewcount"`
	Lastreviwed  pgtype.Date `json:"lastreviwed"`
}

type Woodpeakerset struct {
	ID           pgtype.UUID        `json:"_id"`
	Title        string             `json:"title"`
	UserID       int32              `json:"user_id"`
	Setnumber    int32              `json:"setnumber"`
	Totalpuzzles int32              `json:"totalpuzzles"`
	Minrating    int32              `json:"minrating"`
	Maxrating    int32              `json:"maxrating"`
	Themes       []string           `json:"themes"`
	Status       string             `json:"status"`
	Createdat    pgtype.Timestamptz `json:"createdat"`
	Updatedat    pgtype.Timestamptz `json:"updatedat"`
}

type Woodpeakersetitem struct {
	SetID    pgtype.UUID `json:"set_id"`
	PuzzleID string      `json:"puzzle_id"`
	Position int32       `json:"position"`
}

type Woodpeakersetresult struct {
	ID             pgtype.UUID `json:"_id"`
	SetID          pgtype.UUID `json:"set_id"`
	Attemptnumber  int32       `json:"attemptnumber"`
	Totaltimems    int64       `json:"totaltimems"`
	Solvedclean    int32       `json:"solvedclean"`
	Solvedonretry  int32       `json:"solvedonretry"`
	Failed         int32       `json:"failed"`
	Puzzleattempts []byte      `json:"puzzleattempts"`
	Timebucket     []byte      `json:"timebucket"`
}
