// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changePassword = `-- name: ChangePassword :exec
UPDATE users SET password=$1 WHERE _id=$2
`

type ChangePasswordParams struct {
	Password string `json:"password"`
	ID       int32  `json:"_id"`
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) error {
	_, err := q.db.Exec(ctx, changePassword, arg.Password, arg.ID)
	return err
}

const checkIfusrExists = `-- name: CheckIfusrExists :one
SELECT _id FROM users WHERE email=$1
`

func (q *Queries) CheckIfusrExists(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, checkIfusrExists, email)
	var _id int32
	err := row.Scan(&_id)
	return _id, err
}

const createGame = `-- name: CreateGame :exec
INSERT INTO Games (_id, gameurl, whiteusername, blackusername, whiterating, blackrating, playercolor, timeclass, result, issuecount, user_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type CreateGameParams struct {
	ID            pgtype.UUID `json:"_id"`
	Gameurl       string      `json:"gameurl"`
	Whiteusername string      `json:"whiteusername"`
	Blackusername string      `json:"blackusername"`
	Whiterating   int32       `json:"whiterating"`
	Blackrating   int32       `json:"blackrating"`
	Playercolor   string      `json:"playercolor"`
	Timeclass     string      `json:"timeclass"`
	Result        string      `json:"result"`
	Issuecount    int32       `json:"issuecount"`
	UserID        int32       `json:"user_id"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) error {
	_, err := q.db.Exec(ctx, createGame,
		arg.ID,
		arg.Gameurl,
		arg.Whiteusername,
		arg.Blackusername,
		arg.Whiterating,
		arg.Blackrating,
		arg.Playercolor,
		arg.Timeclass,
		arg.Result,
		arg.Issuecount,
		arg.UserID,
	)
	return err
}

const createGamesBulk = `-- name: CreateGamesBulk :exec
WITH payload AS (
  SELECT
    $1::uuid[] AS ids,
    $2::text[] AS gameurls,
    $3::text[] AS whiteusernames,
    $4::text[] AS blackusernames,
    $5::int4[] AS whiteratings,
    $6::int4[] AS blackratings,
    $7::text[] AS playercolors,
    $8::text[] AS timeclasses,
    $9::text[] AS results,
    $10::int4[] AS issuecounts,
    $11::int4[] AS userids
),
rows AS (
  SELECT
    ids_row.id,
    payload.gameurls[ids_row.idx] AS gameurl,
    payload.whiteusernames[ids_row.idx] AS whiteusername,
    payload.blackusernames[ids_row.idx] AS blackusername,
    payload.whiteratings[ids_row.idx] AS whiterating,
    payload.blackratings[ids_row.idx] AS blackrating,
    payload.playercolors[ids_row.idx] AS playercolor,
    payload.timeclasses[ids_row.idx] AS timeclass,
    payload.results[ids_row.idx] AS result,
    payload.issuecounts[ids_row.idx] AS issuecount,
    payload.userids[ids_row.idx] AS user_id
  FROM payload
  CROSS JOIN LATERAL unnest(payload.ids) WITH ORDINALITY AS ids_row(id, idx)
)
INSERT INTO games (
  _id,
  gameurl,
  whiteusername,
  blackusername,
  whiterating,
  blackrating,
  playercolor,
  timeclass,
  result,
  issuecount,
  user_id
)
SELECT
  rows.id,
  rows.gameurl,
  rows.whiteusername,
  rows.blackusername,
  rows.whiterating,
  rows.blackrating,
  rows.playercolor,
  rows.timeclass,
  rows.result,
  rows.issuecount,
  rows.user_id
FROM rows
ON CONFLICT (_id) DO UPDATE
SET
  gameurl = EXCLUDED.gameurl,
  whiteusername = EXCLUDED.whiteusername,
  blackusername = EXCLUDED.blackusername,
  whiterating = EXCLUDED.whiterating,
  blackrating = EXCLUDED.blackrating,
  playercolor = EXCLUDED.playercolor,
  timeclass = EXCLUDED.timeclass,
  result = EXCLUDED.result,
  issuecount = EXCLUDED.issuecount,
  user_id = EXCLUDED.user_id
`

type CreateGamesBulkParams struct {
	Ids            []pgtype.UUID `json:"ids"`
	Gameurls       []string      `json:"gameurls"`
	Whiteusernames []string      `json:"whiteusernames"`
	Blackusernames []string      `json:"blackusernames"`
	Whiteratings   []int32       `json:"whiteratings"`
	Blackratings   []int32       `json:"blackratings"`
	Playercolors   []string      `json:"playercolors"`
	Timeclasses    []string      `json:"timeclasses"`
	Results        []string      `json:"results"`
	Issuecounts    []int32       `json:"issuecounts"`
	Userids        []int32       `json:"userids"`
}

func (q *Queries) CreateGamesBulk(ctx context.Context, arg CreateGamesBulkParams) error {
	_, err := q.db.Exec(ctx, createGamesBulk,
		arg.Ids,
		arg.Gameurls,
		arg.Whiteusernames,
		arg.Blackusernames,
		arg.Whiteratings,
		arg.Blackratings,
		arg.Playercolors,
		arg.Timeclasses,
		arg.Results,
		arg.Issuecounts,
		arg.Userids,
	)
	return err
}

const createIssue = `-- name: CreateIssue :exec
INSERT INTO Issues (
  _id,
  game_id,
  MoveIndex,
  MoveSAN,
  MoveUCI,
  Fen,
  SideToMove,
  PlayerColor,
  UserColor,
  IssueType,
  PlayedBestMove,
  BestMove,
  Ponder,
  PV,
  Depth,
  ScoreCP,
  Mate,
  AfterScoreCP,
  AfterMate,
  WinProbBefore,
  WinProbAfter
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
  $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
`

type CreateIssueParams struct {
	ID             pgtype.UUID `json:"_id"`
	GameID         pgtype.UUID `json:"game_id"`
	Moveindex      int32       `json:"moveindex"`
	Movesan        string      `json:"movesan"`
	Moveuci        string      `json:"moveuci"`
	Fen            string      `json:"fen"`
	Sidetomove     string      `json:"sidetomove"`
	Playercolor    string      `json:"playercolor"`
	Usercolor      string      `json:"usercolor"`
	Issuetype      string      `json:"issuetype"`
	Playedbestmove bool        `json:"playedbestmove"`
	Bestmove       string      `json:"bestmove"`
	Ponder         string      `json:"ponder"`
	Pv             []string    `json:"pv"`
	Depth          int32       `json:"depth"`
	Scorecp        int32       `json:"scorecp"`
	Mate           int32       `json:"mate"`
	Afterscorecp   int32       `json:"afterscorecp"`
	Aftermate      int32       `json:"aftermate"`
	Winprobbefore  float64     `json:"winprobbefore"`
	Winprobafter   float64     `json:"winprobafter"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) error {
	_, err := q.db.Exec(ctx, createIssue,
		arg.ID,
		arg.GameID,
		arg.Moveindex,
		arg.Movesan,
		arg.Moveuci,
		arg.Fen,
		arg.Sidetomove,
		arg.Playercolor,
		arg.Usercolor,
		arg.Issuetype,
		arg.Playedbestmove,
		arg.Bestmove,
		arg.Ponder,
		arg.Pv,
		arg.Depth,
		arg.Scorecp,
		arg.Mate,
		arg.Afterscorecp,
		arg.Aftermate,
		arg.Winprobbefore,
		arg.Winprobafter,
	)
	return err
}

const getIssues = `-- name: GetIssues :many
SELECT _id, game_id, moveindex, movesan, moveuci, fen, sidetomove, playercolor, usercolor, issuetype, playedbestmove, bestmove, ponder, pv, depth, scorecp, mate, afterscorecp, aftermate, winprobbefore, winprobafter FROM issues WHERE game_id=$1
`

func (q *Queries) GetIssues(ctx context.Context, gameID pgtype.UUID) ([]Issue, error) {
	rows, err := q.db.Query(ctx, getIssues, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Moveindex,
			&i.Movesan,
			&i.Moveuci,
			&i.Fen,
			&i.Sidetomove,
			&i.Playercolor,
			&i.Usercolor,
			&i.Issuetype,
			&i.Playedbestmove,
			&i.Bestmove,
			&i.Ponder,
			&i.Pv,
			&i.Depth,
			&i.Scorecp,
			&i.Mate,
			&i.Afterscorecp,
			&i.Aftermate,
			&i.Winprobbefore,
			&i.Winprobafter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPuzzlesByType = `-- name: GetPuzzlesByType :many
SELECT i._id, i.game_id, i.moveindex, i.movesan, i.moveuci, i.fen, i.sidetomove, i.playercolor, i.usercolor, i.issuetype, i.playedbestmove, i.bestmove, i.ponder, i.pv, i.depth, i.scorecp, i.mate, i.afterscorecp, i.aftermate, i.winprobbefore, i.winprobafter FROM issues i
JOIN games g ON i.game_id = g._id
WHERE g.user_id = $1 AND i.issuetype = $2
ORDER BY i.moveindex
`

type GetPuzzlesByTypeParams struct {
	UserID    int32  `json:"user_id"`
	Issuetype string `json:"issuetype"`
}

func (q *Queries) GetPuzzlesByType(ctx context.Context, arg GetPuzzlesByTypeParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, getPuzzlesByType, arg.UserID, arg.Issuetype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Moveindex,
			&i.Movesan,
			&i.Moveuci,
			&i.Fen,
			&i.Sidetomove,
			&i.Playercolor,
			&i.Usercolor,
			&i.Issuetype,
			&i.Playedbestmove,
			&i.Bestmove,
			&i.Ponder,
			&i.Pv,
			&i.Depth,
			&i.Scorecp,
			&i.Mate,
			&i.Afterscorecp,
			&i.Aftermate,
			&i.Winprobbefore,
			&i.Winprobafter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPuzzlesCount = `-- name: GetPuzzlesCount :one
SELECT COUNT(*) FROM issues i
JOIN games g ON i.game_id = g._id
WHERE g.user_id = $1
`

func (q *Queries) GetPuzzlesCount(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getPuzzlesCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserIssues = `-- name: GetUserIssues :many
SELECT i._id, i.game_id, i.moveindex, i.movesan, i.moveuci, i.fen, i.sidetomove, i.playercolor, i.usercolor, i.issuetype, i.playedbestmove, i.bestmove, i.ponder, i.pv, i.depth, i.scorecp, i.mate, i.afterscorecp, i.aftermate, i.winprobbefore, i.winprobafter FROM issues i
JOIN games g ON i.game_id = g._id
WHERE g.user_id = $1
ORDER BY i.moveindex
`

func (q *Queries) GetUserIssues(ctx context.Context, userID int32) ([]Issue, error) {
	rows, err := q.db.Query(ctx, getUserIssues, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Moveindex,
			&i.Movesan,
			&i.Moveuci,
			&i.Fen,
			&i.Sidetomove,
			&i.Playercolor,
			&i.Usercolor,
			&i.Issuetype,
			&i.Playedbestmove,
			&i.Bestmove,
			&i.Ponder,
			&i.Pv,
			&i.Depth,
			&i.Scorecp,
			&i.Mate,
			&i.Afterscorecp,
			&i.Aftermate,
			&i.Winprobbefore,
			&i.Winprobafter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYourGame = `-- name: GetYourGame :many
SELECT _id, gameurl, whiteusername, blackusername, whiterating, blackrating, playercolor, timeclass, result, issuecount, user_id, createdate FROM games WHERE user_id=$1
`

func (q *Queries) GetYourGame(ctx context.Context, userID int32) ([]Game, error) {
	rows, err := q.db.Query(ctx, getYourGame, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Gameurl,
			&i.Whiteusername,
			&i.Blackusername,
			&i.Whiterating,
			&i.Blackrating,
			&i.Playercolor,
			&i.Timeclass,
			&i.Result,
			&i.Issuecount,
			&i.UserID,
			&i.Createdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginUser = `-- name: LoginUser :one
SELECT _id, fullname,email,password FROM users WHERE email=$1
`

type LoginUserRow struct {
	ID       int32  `json:"_id"`
	Fullname string `json:"fullname"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) LoginUser(ctx context.Context, email string) (LoginUserRow, error) {
	row := q.db.QueryRow(ctx, loginUser, email)
	var i LoginUserRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const registerUser = `-- name: RegisterUser :one
INSERT INTO users (fullname,email,password)
VALUES ($1,$2,$3)
RETURNING _id
`

type RegisterUserParams struct {
	Fullname string `json:"fullname"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, registerUser, arg.Fullname, arg.Email, arg.Password)
	var _id int32
	err := row.Scan(&_id)
	return _id, err
}
